# Generated by Django 4.2.20 on 2025-04-28 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightorder',
            name='create_payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='FlightOrderRetrieveLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retrieve_response_payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flight_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.flightorder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FlightCancelLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancel_request_payload', models.JSONField()),
                ('cancel_response_payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flight_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.flightorder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
