# Generated by Django 4.2.20 on 2025-05-15 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_flightorder_create_payload_flightorderretrievelog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightOfferCandidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_id', models.CharField(max_length=50)),
                ('offer_json', models.JSONField()),
                ('airline', models.CharField(max_length=10)),
                ('departure_airport', models.CharField(max_length=3)),
                ('arrival_airport', models.CharField(max_length=3)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('price', models.CharField(max_length=20)),
                ('number_of_stops', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='booking.flightsearchrecord')),
            ],
        ),
    ]
