# Generated by Django 4.2.20 on 2025-04-28 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotFlightActionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('search', 'Search'), ('booking', 'Booking'), ('cancel', 'Cancel')], max_length=10)),
                ('success', models.BooleanField(default=False)),
                ('origin_location_code', models.CharField(blank=True, max_length=10, null=True)),
                ('destination_location_code', models.CharField(blank=True, max_length=10, null=True)),
                ('departure_date', models.DateField(blank=True, null=True)),
                ('adults', models.IntegerField(blank=True, null=True)),
                ('traveler_name', models.JSONField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raw_chatbot_response', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
