# Generated by Django 4.2.20 on 2025-04-28 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_passportinfo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='passportinfo',
            name='date_of_birth',
            field=models.DateField(default='2000-08-06'),
            preserve_default=False,
        ),
    ]
